FROM python:3

RUN pip install git+https://github.com/blaze/odo.git dask[complete] pymysql SQLAlchemy cryptography pandas &&\
    mkdir -p /opt/importer

COPY importer.py /opt/importer/importer.py

CMD ["python", "/opt/importer/importer.py"]
