START TRANSACTION;

ALTER TABLE measurements MODIFY probe_asn VARCHAR(15) NOT NULL;
ALTER TABLE measurements MODIFY input VARCHAR(600) NOT NULL;

ALTER TABLE summary_measurements MODIFY probe_asn VARCHAR(15) NOT NULL;
ALTER TABLE summary_measurements MODIFY input VARCHAR(600) NOT NULL;

ALTER TABLE sites MODIFY url VARCHAR(600) NOT NULL;
ALTER TABLE sites CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE isp MODIFY asn VARCHAR(12) NOT NULL;

COMMIT;
